#!/bin/bash
# Apply fix to json-fortran fork

echo "Instructions to fix json-fortran Windows compilation issue:"
echo ""
echo "1. Clone the fork (if not already done):"
echo "   git clone https://github.com/krystophny/json-fortran.git"
echo "   cd json-fortran"
echo ""
echo "2. Apply the patch:"
echo "   git apply ../fortran/json-fortran-fix.patch"
echo ""
echo "3. Or manually edit src/json_value_module.F90:"
echo "   - Find the json_get_alloc_string_vec subroutine (around line 9370)"
echo "   - Replace the line:"
echo "     call json%get(me, array_callback=get_chars_from_array)"
echo "   - With:"
echo "     call json_get_alloc_string_vec_alt(json, me, vec, ilen)"
echo "   - Add the new json_get_alloc_string_vec_alt subroutine after json_get_alloc_string_vec"
echo ""
echo "4. Commit and push:"
echo "   git add -A"
echo "   git commit -m 'fix: resolve Windows MinGW GCC 15 internal procedure callback issue'"
echo "   git push origin main"
echo ""
echo "The fix replaces the internal procedure callback with a direct implementation."
